home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    #--swimmer paths
    path('swimmers/', views.SwimmerListView.as_view(), name='swimmers'),
    path('swimmer/create/',views.SwimmerFormView.as_view(),name='add swimmer'),
    path('swimmer/detail/<int:pk>/',views.SwimmerDetailView.as_view(), name = 'detail'),
    path('swimmer/update/<int:pk>/',views.SwimmerUpdateView.as_view(), name = 'update'),

    #-- competition paths
    path('competition/', views.CompetitonMenu.as_view(), name='comp_menu'),
    path('competition/list', views.CompetitionList.as_view(), name='comp_list'),
    path('competition/add',views.CompetitionCreateView.as_view(),name='comp_create'),
    path('competition/detail/<int:pk>/',views.CompRaceView.as_view(),name='comp_detail'),
    path('competition/update/<int:pk>/',views.CompetitionUpdateView.as_view(), name = 'comp_update'),

    #-- race paths
    path('competition/race/detail/<int:pk>/',views.RaceView.as_view(),name='race_detail'),
    path('competition/race/update/<int:pk>/',views.RaceUpdateView.as_view(), name = 'race_update'),

    #-- delete paths
    path('delete-comp/<int:pk>/', views.delete_competition, name='delete_competition'),
    path('delete-swimmer/<int:pk>/', views.delete_swimmer, name='delete_swimmer'),
    path('delete-race/<int:pk>/', views.delete_race, name='delete_race'),
]

swimSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import HttpResponseRedirect

urlpatterns = [
    path('', include('home.urls')), 
    path('admin/', admin.site.urls),
    #path('home/', include('home.urls'))
]

home/forms.py
from django import forms
from django.forms import inlineformset_factory
import datetime
from .models import Swimmer, SwimTime,Competition,Race
from django.utils.translation import gettext as _
from .widgets import MicrosecondWidget
from django.core.exceptions import ValidationError
# create a ModelForm
now =datetime.datetime.now()
class SwimmerForm(forms.ModelForm):
    # specify the name of model to use
    
    class Meta:
        model = Swimmer
        fields = "__all__"
        
        widgets = {
            'dob': forms.SelectDateWidget(years=range(2002,now.year-4))
        }
    
class TimeForm(forms.ModelForm):
    # specify the name of model to use
    
    class Meta:
        model = SwimTime
        fields = ('time', 'distance', 'strokeType', 'date')
        now =datetime.datetime.now()
        widgets = {
            'date': forms.SelectDateWidget(years=range(now.year-5,now.year+1)),
            #TODO time formatting needs to be changed to mm:ss:ms
            #'time': MicrosecondWidget
        }
TimeFormSet = inlineformset_factory(Swimmer,SwimTime,form = TimeForm, extra=0, can_delete = True,can_delete_extra=True)

class CompForm(forms.ModelForm):
    class Meta:
        model= Competition
        fields = ('comp_name','location','start_date','end_date')
        
        widgets = {
            'start_date': forms.SelectDateWidget(),
            'end_date': forms.SelectDateWidget(),
        }
        
    def clean(self):
        super(CompForm, self).clean()
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if(start_date>end_date):
            raise ValidationError(
                _("Error: Start date must be before end date")
            )
        
        
class RaceForm(forms.ModelForm):
    class Meta:
        model= Race
        fields = ('distance','strokeType','age_range_lower','age_range_upper','is_relay')
        
class LinkSwimmersToRaceForm(forms.ModelForm):
    
    class Meta:
        model = Race
        fields = ('swimmers','competition')
        widgets = {
            'swimmers': forms.CheckboxSelectMultiple,
            'competition':forms.HiddenInput
        }
        labels = {
            'swimmers': 'Select swimmers to link to race',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['swimmers'].queryset = Swimmer.objects.all()
        
        self.fields['swimmers'].label_from_instance = lambda obj: f"<td>{obj}</td><td>{obj.find_personal_best(self.instance.distance, self.instance.strokeType)}</td><td>{obj.most_recent_time(self.instance.distance, self.instance.strokeType)}</td>"
        
    
    def save(self):
        swimmers = self.cleaned_data['swimmers']
        #print("\n--------------\nSave func of Link Form\n\n")
        #COMMENT This adds the record(s) to the manytomany link table
        race = self.instance
        race.swimmers.add(*swimmers)

home/views.py
from django.shortcuts import render, redirect
from .models import Swimmer, SwimTime, PersonalBest, Competition,Race
from django.views import generic
#from django.http import HttpResponse
from .forms import SwimmerForm, TimeFormSet,CompForm,RaceForm,LinkSwimmersToRaceForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django_tables2 import SingleTableView
from .tables import SwimmerTable,CompTable
from django.utils import timezone


# Create your views here.



#----------------Home Page View
class HomePageView(generic.TemplateView):
    template_name = "home/home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["noSwimmers"] = Swimmer.objects.all().count()
        context["noTimes"]= SwimTime.objects.all().count()
        nextComp = self.get_next_comp()
        compDate = f"Start Date: {nextComp.start_date}"
        context["nextComp"] = nextComp
        context["compDate"]=compDate
        return context
    def get_next_comp(self):
        today = timezone.datetime.today()
        nextComp = Competition.objects.filter(start_date__gte=today).order_by("start_date").first()
        return nextComp
#----------------Swimmer List View
class SwimmerListView(SingleTableView):
    model = Swimmer
    context_object_name = "swimmers_list"

    table_class = SwimmerTable
    def get_queryset(self):
        fname = self.request.GET.get("fname")
        lname = self.request.GET.get("lname")
        if not fname and not lname:
            fname = ""
            lname = ""
            return super().get_queryset()
        object_list = Swimmer.objects.filter(
            Q(first_name__istartswith=fname)&Q(last_name__istartswith=lname))
        return object_list
    
        

#----------------Add Swimmer View
class SwimmerFormView(generic.FormView):
    form_class=SwimmerForm
    template_name = 'home/add_swimmer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["prevAdded"] = Swimmer.objects.all().order_by('-id')[:5]
        return context
    
    def form_valid(self, form):
        object =form.save()
        pk = object.id
        if self.request.POST.get('view'):
            self.success_url= reverse('home:update', kwargs={'pk':pk})
        elif self.request.POST.get('continue'):
            self.success_url= reverse('home:add swimmer')
        return super(SwimmerFormView, self).form_valid(form)

#----------------Swimmer Detail View
class SwimmerDetailView(generic.DetailView):
    model = Swimmer
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        #COMMENT get_child_objects() returns queryset of swimTimes for access in template
        context['swimTimes']=self.get_child_objects()
        return context
   
    def get_child_objects(self):
        #COMMENT gets swimmer from detailView
        swimmer_object = self.get_object()
        #COMMENT gets queryset of times
        times_objects = swimmer_object.swimtime_set.all()

        if self.request.method == 'GET':
            #COMMENT gets strokeType and distance from search form
            strokeType = self.request.GET.get("strokeType")
            distance = self.request.GET.get("distance")
            #COMMENT if no input in search form set equal to whitespace
            if not strokeType and not distance:
                strokeType=""
                distance=""
            #COMMENT filters through all times for requested times
            times_objects = times_objects.filter(
            Q(strokeType__icontains=strokeType)&Q(distance__icontains=distance))
            
        return times_objects   
    
    #TODO In future, swimmer detail should display upcoming races for swimmers.

#----------------Swimmer Update View
class SwimmerUpdateView(generic.UpdateView):
    model = Swimmer
    template_name = "home/swimmer_update.html"
    form_class = SwimmerForm
    def get_success_url(self):
        return (Swimmer.get_absolute_url(self.object))

    def get_formsets(self):
        return TimeFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='times')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #COMMENT passes CUD time formset to context so it is accessible in template by name formset
        context["formset"] = self.get_formsets()
        return context

    def post(self, request, pk):
        #COMMENT gets Swimmer object, context list, form and formset
        self.object = self.get_object()
        context = self.get_context_data()
        form = SwimmerForm(request.POST, instance=self.object)
        formset = self.get_formsets()
        #COMMENT if Swimmer form invalid re-render template with error
        if not form.is_valid():
            return render(request, self.template_name, context)
        #COMMENT if all swimTime forms (formset) is valid call formset_times_valid() passing formset in
        if formset.is_valid():
            self.formset_times_valid(formset)
        #COMMENT else re-render template with error
        else:
            return render(request, self.template_name, context)
        return super().form_valid(form)

    def formset_times_valid(self, formset):
        #COMMENT instantiates formset as variable
        times = formset.save(commit=False) 
        for obj in formset.deleted_objects:
            obj.delete()
        for time in times:
            time.product = self.object
            time.save()
#----------------Competition Menu View
class CompetitonMenu(generic.TemplateView):
    template_name = "home/competition_menu.html"

#----------------Competition List View
class CompetitionList(SingleTableView):
    model = Competition
    context_object_name ="comp_list"
    table_class = CompTable

    def get_queryset(self):
        status = self.request.GET.get('status', '')
        now = timezone.now()
        if status == 'finished':
            return Competition.objects.filter(end_date__lt=now)
        elif status == 'upcoming_ongoing':
            return Competition.objects.exclude(end_date__lt=now)
        else:
            return Competition.objects.all()
#----------------Competition Create View
class CompetitionCreateView(generic.CreateView):
    model= Competition
    template_name_suffix = '_create'  
    form_class = CompForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["prevAdded"] = Competition.objects.all().order_by('-id')[:5]
        return context

#----------------Competition Detail View
class CompetitionDetailView(generic.DetailView):
    
    model = Competition

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        #COMMENT get_child_objects() returns queryset of swimTimes for access in template
        context['race_form']= RaceForm()
        context['races']=self.get_child_objects()
        return context
    
    def get_child_objects(self):
        #COMMENT gets competition from detailView
        comp_object = self.get_object()
        #COMMENT gets queryset of races
        race_objects = comp_object.race_set.all()

        if self.request.method == 'GET':
            #COMMENT gets strokeType and distance from search form
            strokeType = self.request.GET.get("strokeType")
            distance = self.request.GET.get("distance")
            #COMMENT if no input in search form set equal to whitespace
            if not strokeType and not distance:
                strokeType=""
                distance=""
            #COMMENT filters through all times for requested times
            race_objects = race_objects.filter(
            Q(strokeType__icontains=strokeType)&Q(distance__icontains=distance))
            
        return race_objects   

#----------------Competition Update View
class CompetitionUpdateView(generic.UpdateView):
    model = Competition
    form_class = CompForm
    #COMMENT uses generic update template - DRY
    template_name = "home/generic_update.html"
    #COMMENT passes data in as context to distinguish between models
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_type'] = "Competition"
        context['model'] = self.get_object()
        return context
#----------------Create Race View
class RaceCreateView(generic.CreateView):
    model= Race
      
    template_name = "home/link_swimmers.html"
    form_class = RaceForm
    
    def form_valid(self, form):
        #COMMENT Set the competition for the new race
        form.instance.competition = Competition.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)
    
    def get_success_url(self):
        #COMMENT Redirect to the competition detail page after creating a new race
        return reverse_lazy('home:comp_detail', kwargs={'pk': self.kwargs['pk']})

class RaceUpdateView(generic.UpdateView):
    model = Race
    form_class = RaceForm
    template_name = "home/generic_update.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_type'] = "Race"
        context['model'] = self.get_object()
        return context
#----------------Competition Detail and Create Race Combined View
class CompRaceView(generic.View):
    def get(self, request, *args, **kwargs):
         view = CompetitionDetailView.as_view()
         return view(request, *args, **kwargs) 

    def post(self, request, *args, **kwargs) :
         view = RaceCreateView.as_view()
         return view(request, *args, **kwargs) 

#----------------Race Detail View
class RaceDetailView(generic.DetailView):
    model= Race
    #TODO IM Calculation of fastest combination
    def get_context_data(self, **kwargs):

home/templates/home/competition_detail.html
{%extends 'home/master.html'%}
{% load static %}
{% load render_table from django_tables2 %}
{%block nav_item_comp%}active
{%endblock %}
{%block main%}
<div class="container main">
    <div class="card-deck">
        <div class="card shadow p-2">
            <div class="card-header bg-white">
                <h3>Competition</h3>
            </div>
            <div class="card-body">
                <a class="btn btn-primary mt-2 w-100" href="{% url 'home:comp_update' competition.id %}">Update Competition
                    Details </a>

                <button type="button" class="btn btn-danger mt-2 w-100" data-toggle="modal"
                    data-target="#deleteModal{{competition.pk}}">
                    Delete Competition
                </button>
                <!-- Delete Modal -->
                <div class="modal fade" id="deleteModal{{competition.pk}}" tabindex="-1" role="dialog"
                    aria-labelledby="deleteModalLabel{{competition.pk}}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel{{competition.pk}}">Are You Sure You
                                    Want To Delete This Competition?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'home:delete_competition' competition.pk %}" type="button"
                                    class="btn btn-primary">Yes, Delete</a>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="btn-secondary btn mt-2 w-100" href="{%url 'home:comp_menu' %}">Back</a>
            </div>
        </div>
        <div class="card shadow p-2">
            <div class="card-header bg-white">
                <h3>Competition Details</h3>
            </div>
            <div class="card-body">
                <p><b class="text-secondary">Competition Name:</b> {{ competition.comp_name }}</p>
                <p><b class="text-secondary">Location:</b> {{ competition.location }}</p>
                <p><b class="text-secondary">Start Date:</b> {{ competition.start_date }}</p>
                <p><b class="text-secondary">End Date:</b> {{competition.end_date}}</p>
                <p><b class="text-secondary">Status:</b> {{competition.get_status|safe }}</p>
            </div>
        </div>
        <div class="card shadow p-2 ">
            <div class="card-header bg-white text-center">
                <h3>Races entered at competition</h3>
            </div>
            <div class="card-body align-items-center d-flex justify-content-center">
                <h1 class="display-1">{{competition.race_set.count}}</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="card-group">

        <div class="card shadow p-3">
            <h3>Filter</h3>
            <form action="{% url 'home:comp_detail' competition.id %}" method="get">

                <div class="p-2">
                    <label for="strokeType">Stroke </label><select id="strokeType" name="strokeType">
                        <option value="">Select a Stroke</option>
                        <option value="FC">Front Crawl</option>
                        <option value="BC">Back Crawl</option>
                        <option value="BF">Butterfly</option>
                        <option value="BS">Breast Stroke</option>
                    </select>

                    <label for="distance">Distance </label>
                    <input name="distance" type="number" placeholder="Enter Distance">
                </div>
                <button type="submit" class="btn-primary btn">Search</button>
                <a class="btn-secondary btn" href="{%url 'home:comp_detail' competition.id%}">Back</a>
            </form>
        </div>
        <div class="card shadow p-3">
            <div class="card-body">
                <!-- Modal Trigger -->
                <button type="button" class="btn btn-primary mt-2 w-100" data-toggle="modal" data-target="#raceModal">
                    Add Race
                </button>
                <!-- Modal -->
                <div class="modal fade" id="raceModal" tabindex="-1" role="dialog" aria-labelledby="raceModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="raceModalLabel">Add Race</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="post" action="{%url 'home:comp_detail' competition.id%}">
                                    {% csrf_token %}
                                           
                                    {{ race_form.as_p}}
                        
                                    <button class="btn btn-primary" type="submit" value="view" name="view">Save</button>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="card table-responsive">
        {%if races.count > 0%}

        <table class="table card-body table-striped mb-0 table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Distance</th>
                    <th>Stroke Type</th>
                    <th class="sortable">Age Range</th>
                </tr>
            </thead>
            <tbody>
                {% for r in races %}
                <tr data-href='{{r.get_absolute_url}}'>
                    <td>{{r.distance}}m</td>
                    <td>{{r.strokeType}}</td>
                    <td>{{r.age_range_lower}} - {{r.age_range_upper}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        {%else%}
        <p class="p-3 text-center">Sorry, there are no races matching the filters you entered.
            <br>Please try again with different filters.
        </p>
        {%endif%}
        <!-- allow user to sort by time and filter by date,distance and stroketype  -->
    </div>
</div>
<script>
    $(document).ready(function ($) {
        $("tbody tr").click(function () {
            window.location = $(this).data("href");
        });
    });
</script>
{%endblock %}

home/templates/home/competition_list.html
{%extends 'home/master.html'%}
{% load static %}
{% load render_table from django_tables2 %}
{%block nav_item_comp%}active
{%endblock %}
{%block main%}
<div class="container main">

    <h1>Select Competition</h1>
    <div class="row">
        <div class="col-8" id='details'>
            {%if comp_list %}
            {% render_table table %}
            {% else %}
            <p>No Competitions matching your request are available</p>
            {% endif %}
        </div>
    </div>
    <a class="btn-secondary btn mt-2 " href="{%url 'home:comp_menu' %}">Back</a>
</div>
<script>

    $(document).ready(function ($) {
        $("tbody tr").click(function () {
            window.location = $(this).data("href");
        });
    });
</script>
{%endblock%}

home/templates/home/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--bootstrap links-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <!--list.js link-->
  <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/2.3.1/list.min.js"></script>
  <!--static stylesheet link-->
  <link rel="stylesheet" href="{%static 'home/css/style.css'%}?{% now 'U' %}">

  <title>Swimming Club</title>
</head>

<body class="bg-light">
  <div class="d-flex flex-column shadow sidebar " id="sidebar" aria-expanded="false" data-toggle="collapse">
    <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
      <li class="nav-item">
        <a class="nav-link py-3 border-bottom {% block nav_item_home %}{% endblock nav_item_home %}"
          href="{% url 'home:index' %}">
          <img src="{% static 'home/svg/house-door.svg'%}" width="24" height="24">
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'home:swimmers' %}"
          class="nav-link  py-3 border-bottom {% block nav_item_swimmer_list %}{% endblock nav_item_swimmer_list %}">
          <img src="{% static 'home/svg/person.svg'%}" width="24" height="24">
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'home:add swimmer' %}"
          class="nav-link  py-3 border-bottom {% block nav_item_add_swimmer %}{% endblock nav_item_add_swimmer %}">
          <img src="{% static 'home/svg/person-plus.svg'%}" width="24" height="24">
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'home:comp_menu' %}" class="nav-link  py-3 border-bottom {% block nav_item_comp %}{% endblock nav_item_comp %}">
          <img src="{% static 'home/svg/trophy.svg'%}" width="24" height="24">
        </a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link  py-3 border-bottom {% block nav_item_stats %}{% endblock nav_item_stats %}">
          <img src="{% static 'home/svg/graph-up.svg'%}" width="24" height="24">
        </a>
      </li>
    </ul>
  </div>
  {%block main%}
  {%endblock%}
</body>
<style>
  @media (max-width:450px) {
    .main {
      padding-left: 5rem !important;
    }
  }

  @media (max-width:768px) and (min-width:451px) {
    .main {
      padding-left: 5rem !important;
    }
  }

  @media (min-width:769px) {
    .main {
      padding-left: 4rem !important;
    }
  }
</style>

</html>

home/templates/home/swimmer_detail.html
{% extends "home/master.html" %}
{% load static %}
{% block nav_item_swimmer_list %}active{% endblock nav_item_swimmer_list %}
{% block main %}
<div class="container main">
    <div class="card-deck">
        <div class="card shadow p-2">
            <div class="card-header bg-white">
                <h3>Swimmer</h3>
            </div>
            <div class="card-body">
                <a class="btn btn-primary mt-2 w-100" href="{% url 'home:update' swimmer.id %}">Update Details or Add
                    Times</a>
                    
                    <button type="button" class="btn btn-danger mt-2 w-100" data-toggle="modal"
                    data-target="#deleteModal{{swimmer.pk}}">
                    Delete Swimmer
                </button>
                <!-- Modal -->
                <div class="modal fade" id="deleteModal{{swimmer.pk}}" tabindex="-1" role="dialog"
                    aria-labelledby="deleteModalLabel{{swimmer.pk}}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel{{swimmer.pk}}">Are You Sure You
                                    Want To Delete This Swimmer?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'home:delete_swimmer' swimmer.pk %}" type="button"
                                    class="btn btn-primary">Yes, Delete</a>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="btn-secondary btn mt-2 w-100" href="{%url 'home:swimmers' %}">Back</a>
            </div>
        </div>
        <div class="card shadow p-2">
            <div class="card-header bg-white">
                <h3>Swimmer Details</h3>
            </div>
            <div class="card-body">
                <p><b class="text-secondary">First Name:</b> {{ swimmer.first_name }}</p>
                <p><b class="text-secondary">Last Name:</b> {{ swimmer.last_name }}</p>
                <p><b class="text-secondary">Date of Birth:</b> {{ swimmer.dob }}</p>
                <p><b class="text-secondary">Age:</b> {{swimmer.get_age}}</p>
            </div>
        </div>
        <div class="card shadow p-2 ">
            <div class="card-header bg-white">
                <h3>Total Times Recorded</h3>
            </div>
            <div class="card-body align-items-center d-flex justify-content-center">
                <h1 class="display-1">{{swimmer.swimtime_set.count}}</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="card shadow p-3">
        <h3>Filter</h3>
        <form action="{% url 'home:detail' swimmer.id %}" method="get">
            
            <div class="p-2">
                <label for="strokeType">Stroke </label><select id="strokeType" name="strokeType">
                    <option value="">Select a Stroke</option>
                    <option value="FC">Front Crawl</option>
                    <option value="BC">Back Crawl</option>
                    <option value="BF">Butterfly</option>
                    <option value="BS">Breast Stroke</option>
                </select>

                <label for="distance">Distance </label>
                <input name="distance" type="number" placeholder="Enter Distance">
            </div>
            <button type="submit" class="btn-primary btn">Search</button>
            <a class="btn-secondary btn" href="{%url 'home:detail' swimmer.id%}">Clear Filters</a>
        </form>
    </div>
    <hr>
    <div class="card table-responsive">
        {%if swimTimes.count > 0%}
        
        <table class="table card-body table-striped mb-0">
            <thead class="thead-dark">
                <tr>
                    <th class="sortable">Time</th>
                    <th>Distance</th>
                    <th>Stroke Type</th>
                    <th>Date Recorded</th>
                    <th>Difference from PB</th>
                </tr>
            </thead>
            <tbody>
                {% for t in swimTimes %}
                <tr>
                    <td>{{t.get_time}}</td>
                    <td>{{t.distance}}</td>
                    <td>{{t.strokeType}}</td>
                    <td>{{t.date}}</td>
                    
                    <td>
                        {%if t.find_difference%}
                            <span class="text-danger">+{{t.find_difference}}</span>
                        {%else%}
                            <b class="text-success">Personal Best</b>
                        {%endif%}
                    </td>
                </tr>
                {%endfor%}

            </tbody>
        </table>
        {%else%}
        <p class="p-3 text-center">Sorry, there are no swim times matching the filters you entered. 
            <br>Please try again with different filters.</p>
        {%endif%}
        <!-- allow user to sort by time and filter by date,distance and stroketype  -->
    </div>
    
</div>
{% endblock main %}

home/templates/home/test.html
{%extends 'home/master.html'%}
{% load render_table from django_tables2 %}
{% load static %}
{%block nav_item_swimmer_list%}active
{%endblock %}
{%block main%}
<div class=" container main">
    {% render_table table %}
</div>
{%endblock%}